#!/usr/bin/env bash

###########################
# Colours
###########################

BOLD="\e[1m"

CYAN="\e[36m"
GREEN="\e[32m"
RED="\e[31m"
YELLOW="\e[33m"

RESET="\e[0m"

###########################
# PWD
###########################

PWD="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

flake8 --config=${PWD}/../setup.cfg ${PWD}/../py_trees ${PWD}/../tests

if [ $? -eq 0 ]; then
  echo -e "${GREEN} I'm grooty, you should be too.${RESET}"
else
  echo -e "${RED} Not grooty, see above for error details.${RESET}"
fi
