#!/usr/bin/env python
#
# License: Yujin
#
##############################################################################
# Documentation
##############################################################################
"""
Node that manages map switching and teleports.
"""
##############################################################################
# Imports
##############################################################################

import marco_polo
import rospy

##############################################################################
# Main
##############################################################################

if __name__ == '__main__':

    rospy.init_node('marco_polo', log_level=rospy.INFO)

    node = marco_polo.Node()

    try:
        rospy.spin()
    except rospy.ROSInterruptException:
        pass

    node.shutdown()
