#!/usr/bin/env python

import rospy
import unique_id
import py_trees.msg as py_trees_msgs

if __name__ == '__main__':
    rospy.init_node("tmp")

    pub = rospy.Publisher("~test", py_trees_msgs.BehaviourTree, queue_size=1)
    rate = rospy.Rate(1)
    
    while not rospy.is_shutdown():
        beht = py_trees_msgs.BehaviourTree()
        beh = py_trees_msgs.Behaviour()
        beh.own_id = unique_id.toMsg(unique_id.fromRandom())
        beh.child_ids = [unique_id.toMsg(unique_id.fromRandom()) for i in range(0, 5)]
        beht.behaviours.append(beh)
        pub.publish(beht)
        rate.sleep()
