#!/usr/bin/env python
#
# License: BSD
#   https://raw.github.com/yujinrobot/gopher_crazy_hospital/license/LICENSE
#
##############################################################################
# Imports
##############################################################################

import argparse
import geometry_msgs.msg as geometry_msgs
import gopher_behaviours
import gopher_configuration
import py_trees
import rocon_console.console as console
import rospy
import sys

##############################################################################
# Arg Parsing
##############################################################################


def show_description():
    s = "\n"
    s += console.green + "This will test the move base behaviour by moving to (1.0, 0.0, 0.0)." + console.reset
    s += console.green + "Best tested if your robot is currently at the origin!" + console.reset
    s += console.yellow + "TODO : could use an upate to move 1m ahead of the current location" + console.reset
    s += console.yellow + "by making use of the CheckSubscriberVariable on the /navi/pose topic." + console.reset
    s += "\n"
    return s


def show_usage():
    s = "\n"
    s += console.white
    s += console.bold + "************************************************************************************\n" + console.reset
    s += console.bold + "                              Demo Move Base\n" + console.reset
    s += console.bold + "************************************************************************************\n" + console.reset
    s += "\n"
    s += console.white
    s += console.bold + "    Generate Dot" + console.reset + "\n"
    s += console.cyan + "        demo_move_base" + console.yellow + " --render" + console.reset + "\n"
    s += "\n"
    s += console.bold + "    Execute" + console.reset + "\n"
    s += console.cyan + "        demo_move_base" + console.yellow + " [options]" + console.reset + "\n"
    s += "\n"
    s += console.white
    s += console.bold + "    Required Launchers" + console.reset + "\n"
    s += console.cyan + "        + minimal.launch" + console.reset + "\n"
    s += console.cyan + "        + fake_navigation.launch" + console.reset + "\n"
    s += "\n"
    return s


def parse_arguments(command_line_args):
    parser = argparse.ArgumentParser(description=show_description(),
                                     usage=show_usage(),
                                     epilog="And his noodly appendage reached forth to tickle the blessed...",
                                     formatter_class=argparse.ArgumentDefaultsHelpFormatter
                                     )
    parser.add_argument('-r', '--render', action='store_true', help='render the graph to dot/png/svg.')
    parser.add_argument('-d', '--debug', action='store_true', help='debug level tree logging.')

    args = parser.parse_args(command_line_args)
    return args

##############################################################################
# Tree
##############################################################################


class Demo(object):
    def __init__(self):
        self.gopher = gopher_configuration.Configuration()
        self.logger = py_trees.logging.get_logger("MoveBase")
        pose = geometry_msgs.Pose2D()
        pose.x = 1.0
        pose.y = 0.0
        pose.theta = 0.0
        self.root = gopher_behaviours.navigation.MoveIt(
            "Demo MoveBase",
            pose,
            dont_ever_give_up=False
        )
        self.tree = py_trees.ROSBehaviourTree(self.root)
        rospy.on_shutdown(self.shutdown)

    ##############################################################################
    # Tick Tock
    ##############################################################################

    def tick_tock(self):
        self.tree.visitors.append(gopher_behaviours.utilities.DebugVisitor())
        rate = rospy.Rate(10)
        while not rospy.is_shutdown():
            self.tree.tick(pre_tick_handler=self.pre_tick_handler)
            if self.root.status == py_trees.Status.SUCCESS or self.root.status == py_trees.Status.FAILURE:
                break
            rate.sleep()

    def pre_tick_handler(self, behaviour_tree):
        self.logger.debug("")
        self.logger.debug("{:-^30}".format(" Run %s " % behaviour_tree.count))
        self.logger.debug("")

    def shutdown(self):
        self.tree.destroy()  # destroy the tree on shutdown to stop the behaviour
        self.tree.interrupt()

##############################################################################
# Main
##############################################################################

if __name__ == '__main__':
    command_line_args = rospy.myargv(argv=sys.argv)[1:]
    args = parse_arguments(command_line_args)
    if args.debug:
        py_trees.logging.level = py_trees.logging.Level.DEBUG

    demo = Demo()
    if args.render:
        py_trees.display.print_ascii_tree(demo.root, 0)
        py_trees.display.render_dot_tree(demo.root)
        sys.exit()

    rospy.init_node("demo", log_level=rospy.INFO)
    if not demo.tree.setup(5):
        sys.exit(console.red + "[ERROR] failed to setup required ros components." + console.reset)
    demo.tick_tock()
