#!/usr/bin/env python
#
# License: BSD
#   https://raw.github.com/yujinrobot/gopher_crazy_hospital/license/LICENSE
#
##############################################################################
# Documentation
##############################################################################
"""
USE THE ROS LAUNCHER INSTEAD!!!

gopher_behaviours/demo_move_base.launch
"""
##############################################################################
# Imports
##############################################################################

import geometry_msgs.msg as geometry_msgs
import gopher_behaviours
import gopher_configuration
import py_trees
# import rocon_console.console as console
import rospy

##############################################################################
# Tree
##############################################################################


class DemoMoveBase(object):
    def __init__(self):
        self.gopher = gopher_configuration.Configuration()
        self.logger = py_trees.logging.get_logger("MoveBase")
        distance = rospy.get_param("~distance", 0.5)
        pose = geometry_msgs.Pose2D()
        pose.x = distance
        pose.y = 0.0
        pose.theta = 0.0
        self.root = gopher_behaviours.navigation.MoveIt(
            "MoveBase",
            pose,
            dont_ever_give_up=False
        )
        self.tree = py_trees.ROSBehaviourTree(self.root)
        rospy.on_shutdown(self.shutdown)
        # py_trees.display.render_dot_tree(self.root)
        py_trees.display.print_ascii_tree(self.root, 0)

    def wait_for_ros(self):
        if not self.root.setup(15.0):
            rospy.logerr("SimpleMotions: failed to find the simple motions action server.")

    ##############################################################################
    # Tick Tock
    ##############################################################################

    def tick_tock(self):
        self.tree.visitors.append(gopher_behaviours.utilities.DebugVisitor())
        rate = rospy.Rate(10)
        while not rospy.is_shutdown():
            self.tree.tick(pre_tick_handler=self.pre_tick_handler)
            if self.root.status == py_trees.Status.SUCCESS or self.root.status == py_trees.Status.FAILURE:
                break
            rate.sleep()

    def pre_tick_handler(self, behaviour_tree):
        self.logger.debug("")
        self.logger.debug("{:-^30}".format(" Run %s " % behaviour_tree.count))
        self.logger.debug("")

    def shutdown(self):
        self.tree.destroy()  # destroy the tree on shutdown to stop the behaviour
        self.tree.interrupt()

##############################################################################
# Main
##############################################################################

if __name__ == '__main__':
    py_trees.logging.level = py_trees.logging.Level.DEBUG
    rospy.init_node("demo_move_base", log_level=rospy.DEBUG)

    move_base = DemoMoveBase()
    move_base.wait_for_ros()
    move_base.tick_tock()
