#!/usr/bin/env python
#
# License: BSD
#   https://raw.github.com/yujinrobot/gopher_crazy_hospital/license/LICENSE
#
##############################################################################
# Documentation
##############################################################################
"""
USE THE ROS LAUNCHER INSTEAD!!!

gopher_behaviours/demo_switch_map.launch

"""
##############################################################################
# Imports
##############################################################################

import gopher_behaviours
import gopher_semantics
import os
import py_trees
import rospy

##############################################################################
# Core Controller
##############################################################################


class SwitchMap(object):
    def __init__(self, map_name):
        self.root = py_trees.Sequence("SwitchMap")
        self.parameters = gopher_behaviours.Parameters()
        self.semantics = gopher_semantics.Semantics(self.parameters.namespaces.semantics)
        self.logger = py_trees.logging.get_logger("SwitchMap")
        map_filename = os.path.join(gopher_behaviours.utilities.get_gopher_home(), "maps", map_name + ".dslam")
        switch_map = gopher_behaviours.navigation.SwitchMap("SwitchMap", map_filename, self.parameters.topics.switch_map)
        try:
            destination = self.semantics.elevators.find_level_on_elevator('highway_to_hell', map_name)
            init_pose = gopher_behaviours.navigation.InitPose("InitPose", destination.exit, self.parameters.topics.initial_pose)
        except AttributeError:
            rospy.logerr("Switch Map: no elevators found, wrong semantics loaded [%s]?\n%s" % (self.parameters.namespaces.semantics, str(self.semantics)))
            return

        self.root.add_child(switch_map)
        self.root.add_child(init_pose)
        self.tree = py_trees.ROSBehaviourTree(self.root)

        rospy.on_shutdown(self.shutdown)

        py_trees.display.render_dot_tree(self.root)

    ##############################################################################
    # Tick Tock
    ##############################################################################

    def tick_tock(self):
        loop_around = rospy.Rate(10)
        self.tree.visitors.append(gopher_behaviours.utilities.DebugVisitor())
        while self.root.status != py_trees.Status.SUCCESS and not rospy.is_shutdown():
            self.tree.tick(pre_tick_handler=self.pre_tick_handler)
            loop_around.sleep()

    def pre_tick_handler(self, behaviour_tree):
        self.logger.debug("")
        self.logger.debug("{:-^30}".format(" Run %s " % behaviour_tree.count))
        self.logger.debug("")

    def shutdown(self):
        self.tree.destroy()  # destroy the tree on shutdown to stop the behaviour
        self.tree.interrupt()

##############################################################################
# Main
##############################################################################

if __name__ == '__main__':
    py_trees.logging.level = py_trees.logging.Level.DEBUG
    rospy.init_node("flash_and_wait", log_level=rospy.DEBUG)
    map = rospy.get_param("~map", 'hell')
    flash_and_wait = SwitchMap(map)
    flash_and_wait.tick_tock()
