#!/usr/bin/env python
#
# License: BSD
#   https://raw.github.com/yujinrobot/gopher_crazy_hospital/license/LICENSE
#
##############################################################################
# Documentation
##############################################################################
"""
USE THE ROS LAUNCHER INSTEAD!!!

gopher_behaviours/demo_flash_and_wait.launch
"""
##############################################################################
# Imports
##############################################################################

import gopher_behaviours
import py_trees
import rospy

##############################################################################
# Core Controller
##############################################################################


class DemoHomebaseRecovery(object):
    def __init__(self):
        self.root = gopher_behaviours.recovery.HomebaseRecovery("HomeBaseRecovery")
        self.logger = py_trees.logging.get_logger("FlashAndWait")
        self.tree = py_trees.ROSBehaviourTree(self.root)

        rospy.on_shutdown(self.shutdown)

        py_trees.display.render_dot_tree(self.root)

    ##############################################################################
    # Tick Tock
    ##############################################################################

    def tick_tock(self):
        self.tree.visitors.append(gopher_behaviours.utilities.DebugVisitor())
        self.tree.tick_tock(sleep_ms=500, number_of_iterations=py_trees.CONTINUOUS_TICK_TOCK, pre_tick_handler=self.pre_tick_handler)

    def pre_tick_handler(self, behaviour_tree):
        self.logger.debug("")
        self.logger.debug("{:-^30}".format(" Run %s " % behaviour_tree.count))
        self.logger.debug("")

    def shutdown(self):
        self.tree.destroy()  # destroy the tree on shutdown to stop the behaviour
        self.tree.interrupt()

##############################################################################
# Main
##############################################################################

if __name__ == '__main__':
    py_trees.logging.level = py_trees.logging.Level.DEBUG
    rospy.init_node("flash_and_wait", log_level=rospy.DEBUG)
    flash_and_wait = DemoHomebaseRecovery()
    flash_and_wait.tick_tock()
