#!/usr/bin/env python

import rospy
import std_msgs.msg as std_msgs
import door_interactions_msgs.msg as door_msgs


class dt(object):
    def __init__(self):
        inst_sub = rospy.Subscriber("/door_basic/command", std_msgs.Bool, self.instr, queue_size=1)
        self.sub = rospy.Subscriber("/concert/door_operator/response", door_msgs.DoorControlPairResponse, self.callb, queue_size=1)
        self.p = rospy.Publisher("/concert/door_operator/request", door_msgs.DoorControlPairRequest, queue_size=1)

        lr = rospy.Rate(1)
        while not rospy.is_shutdown():
            lr.sleep()

    def instr(self, msg):
        req = door_msgs.DoorControlPairRequest()
        if msg.data:
            req.request.cmd = door_msgs.DoorControlRequest.OPEN_DOOR
        else:
            req.request.cmd = door_msgs.DoorControlRequest.CLOSE_DOOR

        self.p.publish(req)
        
    def callb(self, msg):
        print(msg)

if __name__ == '__main__':
    rospy.init_node("dtnode")
    dd = dt()
