#!/usr/bin/env python

import rospy
import std_msgs.msg as std_msgs


class dt(object):
    def __init__(self):
        sub = rospy.Subscriber("/concert/door_status", std_msgs.String, self.callb, queue_size=1)
        p = rospy.Publisher("/concert/door_ctrl", std_msgs.Bool, queue_size=1)

        lr = rospy.Rate(1)
        while not rospy.is_shutdown():
            lr.sleep()
    
    def callb(self, msg):
        print(msg)

if __name__ == '__main__':
    rospy.init_node("dtnode")
    dd = dt()