#!/usr/bin/env python

import argparse
import gopher_behaviours
import py_trees
import rocon_console.console as console
import rospy
import sys


##############################################################################
# Arg Parsing
##############################################################################


def show_description():
    s = "\n"
    s += console.green + "This node runs the delivery behaviour tree for gophers." + console.reset
    s += "\n"
    return s


def show_usage():
    s = "\n"
    s += console.white
    s += console.bold + "************************************************************************************\n" + console.reset
    s += console.bold + "                                Gopher Deliveries\n" + console.reset
    s += console.bold + "************************************************************************************\n" + console.reset
    s += "\n"
    s += console.white
    s += console.bold + "    Generate Dot" + console.reset + "\n"
    s += console.cyan + "        gopher_deliveries" + console.yellow + " --render" + console.reset + "\n"
    s += "\n"
    s += console.cyan + "        + gopher_deliveries.launch" + console.reset + "\n"
    s += console.bold + "    RosLaunch" + console.reset + "\n"
    s += console.cyan + "        roslaunch gopher_behaviours gopher_deliveries.launch" + console.reset + "\n"
    s += "\n"
    s += console.white
    s += console.bold + "    Requrired Launchers" + console.reset + "\n"
    s += console.cyan + "        + gopher_robot/minimal.launch" + console.reset + "\n"
    s += console.cyan + "        + ...(many - bring up instead with rapps)" + console.reset + "\n"
    s += console.cyan + "        or" + console.reset
    s += console.cyan + "        + gopher_desktop/gocart_sim.launch" + console.reset + "\n"
    s += "\n"
    s += console.white
    s += console.bold + "    Rapps" + console.reset + "\n"
    s += console.cyan + "        + gopher_robot/gocart_delivery" + console.reset + "\n"
    s += console.cyan + "        + ...(many - bring up instead with rapps)" + console.reset + "\n"
    s += "\n"
    return s


def parse_arguments(command_line_args):
    parser = argparse.ArgumentParser(description=show_description(),
                                     usage=show_usage(),
                                     epilog="And his noodly appendage reached forth to tickle the blessed...",
                                     formatter_class=argparse.ArgumentDefaultsHelpFormatter
                                     )
    parser.add_argument('-r', '--render', action='store_true', help='render the graph to dot/png/svg.')

    args = parser.parse_args(command_line_args)
    return args

##############################################################################
# Main
##############################################################################

if __name__ == '__main__':
    myargs = rospy.myargv(argv=sys.argv)
    args = parse_arguments(command_line_args=myargs[1:])

    if args.render:
        gopher_compulsion = gopher_behaviours.hive_mind.GopherHiveMind()
        gopher_compulsion.render_dot_tree()
        sys.exit()

    # have to read debug param before initialising node, it's not possible to
    # change the log level after node is initialised.
    debug_mode = rospy.get_param("/gopher_deliveries/debug", False) or args.debug
    log_lev = rospy.INFO
    if debug_mode:
        py_trees.logging.level = py_trees.logging.Level.DEBUG
        log_lev = rospy.DEBUG

    rospy.init_node("gopher_compulsion", log_level=log_lev)

    gopher_compulsion = gopher_behaviours.hive_mind.GopherHiveMind()
    gopher_compulsion.setup(30)
    gopher_compulsion.tick_tock()
