#!/usr/bin/env python
#
# License: BSD
#   https://raw.github.com/yujinrobot/gopher_crazy_hospital/license/LICENSE
#
##############################################################################
# Documentation
##############################################################################
"""
Simple demo program for py trees
"""
##############################################################################
# Imports
##############################################################################

import argparse
import gopher_behaviours
import py_trees
import rospy

##############################################################################
# Classes
##############################################################################


def show_usage(root):
    print("")
    print("************************************************************************************")
    print("                                 Gopher Compulsion")
    print("************************************************************************************")
    print("")
    print("Warm, fuzzy, furry, behavioural experiments")
    print("")
    py_trees.display.print_ascii_tree(root)
    print("")
    print("************************************************************************************")
    print("")

##############################################################################
# Main
##############################################################################

if __name__ == '__main__':
    rospy.init_node("gopher_compulsion", log_level=rospy.DEBUG)
    py_trees.logging.level = py_trees.logging.Level.DEBUG

    gopher_compulsion = gopher_behaviours.GopherCompulsion()

    parser = argparse.ArgumentParser(description='Gopher Compulsion', usage=show_usage(gopher_compulsion.tree.root))
    unused_args = parser.parse_args()

    gopher_compulsion.tick_tock()
