#!/usr/bin/env python
#
# License: Yujin
#
##############################################################################
# Documentation
##############################################################################
"""
Simple demo program for the gopher behaviour parameter store.
"""
##############################################################################
# Imports
##############################################################################

import gopher_configuration
import os
import rocon_console.console as console
import rospkg
import yaml

##############################################################################
# Core Controller
##############################################################################


##############################################################################
# Main
##############################################################################

if __name__ == '__main__':
    gopher_configuration.Configuration.load_defaults()
    gopher = gopher_configuration.Configuration()
    print("%s" % gopher)

    # you could also launch gopher_configuration/gopher_configuration.launch
    # and then:
    #
    # gopher = gopher_configuration.Configuration()
    #
    # would automatically retrieve the configuration from the
    # /gopher/configuration namespace on the rosparam server (no manual
    # loading in code necessary)
