#!/usr/bin/env python
#
# License: Unspecified
#
##############################################################################
# Imports
##############################################################################

import gopher_semantics
import rospy

##############################################################################
# Main
##############################################################################

if __name__ == '__main__':
    rospy.init_node('map_locations')
    map_locations = gopher_semantics.MapLocations()
    map_locations.spin()
