name: pre-merge

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

on:
  pull_request:
  workflow_dispatch:

jobs:
  pre-merge:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ["3.8", "3.10"]
        include:
          - python-version: "3.8"
            python-py-version: "py38"
          - python-version: "3.10"
            python-py-version: "py310"
    container:
      image: ghcr.io/${{ github.repository }}:${{ matrix.python-py-version }}-poetry-bullseye
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v3
    - name: Find the Poetry Cache
      run: |
        echo "POETRY_CACHE_DIR=$(poetry config virtualenvs.path)" >> $GITHUB_ENV
        echo "POETRY_CACHE_DIR: ${{ env.POETRY_CACHE_DIR }}"

    - name: Cache the Poetry Cache
      id: cache-deps
      uses: actions/cache@v3
      with:
        path: ${POETRY_CACHE_DIR}
        # bump the suffix if you need to force-refresh the cache
        key: dependencies-${{ matrix.python-version }}-${{ hashFiles('**/poetry.lock') }}-1

    # Install all deps, sans the project (--no-root)
    - name: Install Dependencies
      run: poetry install --no-interaction --no-root
      if: steps.cache-deps.outputs.cache-hit != 'true'

    # Project is installed separately to avoid always invalidating the cache
    - name: Install Project
      run: poetry install --no-interaction

    # TODO: Caching above doesn't make much sense when tox effectively re-installs deps
    - name: Tests
      run: poetry run tox -e ${{ matrix.python-py-version }}
    - name: Formatters, Linters
      run: poetry run tox -e check
    - name: MyPy
      run: poetry run tox -e my${{ matrix.python-py-version }}
