################################################################################
# Store a cache for dependencies on every merge to devel.
#
# All PR's have access to devel's caches. This makes sure it gets generated and
# is available for the next PR. Otherwise every PR will always generate a cache
# for the first commit of the PR (subsequent commits will reuse that).
#
# https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows
################################################################################
name: update-poetry-cache

on:
  push:
    branches:
      - devel
  workflow_dispatch:

jobs:
  update-poetry-cache:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: ["3.8", "3.10"]
        include:
          - python-version: "3.8"
            python-py-version: "py38"
          - python-version: "3.10"
            python-py-version: "py310"
    container:
      image: ghcr.io/${{ github.repository }}-ci:${{ matrix.python-py-version }}-poetry-bullseye
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v3
    - name: Poetry Cache Dir
      run: |
        echo "POETRY_CACHE_DIR=$(poetry config virtualenvs.path)" >> $GITHUB_ENV

    - name: Poetry Cache from Cache
      id: cache-deps
      uses: actions/cache@v3
      with:
        path: ${{ env.POETRY_CACHE_DIR }}
        # bump the suffix if you need to force-refresh the cache
        key: poetry-cache-${{ matrix.python-version }}-${{ hashFiles('**/poetry.lock') }}-1

    # Install all deps, sans the project (--no-root)
    - name: Install Dependencies
      run: poetry install --no-interaction --no-root
      if: steps.cache-deps.outputs.cache-hit != 'true'


